### ISSUE TITLE
Aew

### ISSUE THREAD

**Issue by Capaverde** [WeetchKing/WeetchKing.github.io#1]
Bom trabalho. Tem app do VT?

**Comment by Capaverde** [comment]
Ah é, Leal e Mau aqui btw. Tô pensando em começar a mexer pra Android, mas isso final desse ano ou começo do próximo.

**Comment by Capaverde** [comment]
Ah cara, vou criar uma app do VT. Não será nesse mês mas certamente nesse ano.

**Comment by WeetchKing** [comment]
vai q e tua
